language: r
r:
  - release
  - oldrel

allow_failures:
  - r: oldrel

# Avoid using packages in the cache
# cache: packages

os:
  - linux

sudo: required

#fussy building for CRAN compatibility
warnings_are_errors: true
r_check_args: --as-cran

r_binary_packages:
  - Rcpp
  - R6

r_packages:
  - Matrix
  - methods

# dump the R install check log
after_script:  cat ${RCHECK_DIR}/00install.out

matrix:
  include:
    - os: osx
      r: release
      disable_homebrew: true
    - os: osx
      r: release
      disable_homebrew: false
    - os: osx
      r: oldrel
      disable_homebrew: true
    - os: osx
      r: oldrel
      disable_homebrew: false
